spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false